versions.fabricloader = "0.19.3"
versions.devauth = "1.2.2"
versions.hypixelmodapi = "1.0.1.2"

["26.2-fabric"]
versioning = "single"
versions.fabricapi = "0.158.0+26.2"
versions.oneconfig = "1.1.12"
versions.modmenu = "20.0.1"

["26.1-fabric"]
versioning = "range"
mc.max = "26.1.2"
versions.fabricapi = "0.155.2+26.1.2"
versions.oneconfig = "1.1.12"
versions.modmenu = "18.0.0"

["1.8.9-forge"]
versioning = "single"
versions.oneconfig = "0.2.2-alpha+"
versions.oneconfigwrapper = "1.0.0-beta+"

["1.8.9-fabric"]
versioning = "single"
versions.oneconfig = "1.1.12"
versions.osl = "0.20.3"
versions.oslcore = "0.9.0+mc14w27a-mc1.14.4"
versions.oslentrypoints = "0.6.1+mc13w16a-mc1.14.4"
versions.oslnetworking = "0.9.0+mc13w41a-mc18w30b"